
numeros = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
suma_numeros = sum(numeros)
print(f"La suma de los elementos de la tupla es: {suma_numeros}")
valor_maximo = max(numeros)
valor_minimo = min(numeros)
print(f"El valor máximo de la tupla es: {valor_maximo}")
print(f"El valor mínimo de la tupla es: {valor_minimo}")
cantidad_cinco = numeros.count(5)
print(f"El número 5 aparece {cantidad_cinco} vez/veces en la tupla")
